import hashlib
import json
import os
from app.core.config import settings

# ─── Graceful web3 import ────────────────────────────────────────────────────
try:
    from web3 import Web3
    _web3_available = True
except ImportError:
    _web3_available = False
    print("Warning: web3 not installed. Blockchain features disabled. Run: pip install web3")

# ─── Contract Setup ──────────────────────────────────────────────────────────
_w3 = None
_contract = None

def _get_web3():
    global _w3
    if not _web3_available:
        return None
    if _w3 is None and settings.POLYGON_RPC:
        _w3 = Web3(Web3.HTTPProvider(settings.POLYGON_RPC))
    return _w3

def _get_contract():
    global _contract
    if _contract is not None:
        return _contract
    
    w3 = _get_web3()
    if not w3:
        return None
    
    contract_address = getattr(settings, "CONTRACT_ADDRESS", None)
    if not contract_address:
        return None
    
    # Load ABI from file (generated by Hardhat deploy)
    abi_path = os.path.join(os.path.dirname(__file__), "../../contract_abi.json")
    if not os.path.exists(abi_path):
        print("Warning: contract_abi.json not found. Deploy the contract first.")
        return None
    
    with open(abi_path) as f:
        abi = json.load(f)
    
    _contract = w3.eth.contract(
        address=Web3.to_checksum_address(contract_address),
        abi=abi
    )
    return _contract

# ─── Core Functions ──────────────────────────────────────────────────────────

def generate_property_hash(property_data: dict) -> str:
    """
    Generates a deterministic SHA-256 hash of property data.
    Only critical fields are hashed (not timestamps/IDs which change).
    """
    # Use only stable, meaningful fields for the hash
    stable_data = {
        "title": property_data.get("title", ""),
        "price": property_data.get("price", 0),
        "address": property_data.get("address", ""),
        "owner_id": str(property_data.get("owner_id", "")),
        "location": property_data.get("location", {})
    }
    data_string = json.dumps(stable_data, sort_keys=True)
    return hashlib.sha256(data_string.encode()).hexdigest()

def verify_property_on_chain(property_hash: str) -> dict:
    """
    Sends a verifyProperty transaction to the smart contract.
    Returns tx_hash on success, or a mock result if blockchain is unavailable.
    """
    contract = _get_contract()
    w3 = _get_web3()
    
    # Graceful fallback: blockchain not configured
    if not contract or not w3:
        return {
            "success": False,
            "tx_hash": None,
            "mode": "offline",
            "message": "Blockchain not configured. Set POLYGON_RPC, CONTRACT_ADDRESS, WALLET_ADDRESS, PRIVATE_KEY."
        }
    
    wallet = getattr(settings, "WALLET_ADDRESS", None)
    private_key = getattr(settings, "PRIVATE_KEY", None)
    
    if not wallet or not private_key:
        return {
            "success": False,
            "tx_hash": None,
            "mode": "offline",
            "message": "Wallet credentials not configured."
        }
    
    try:
        tx = contract.functions.verifyProperty(property_hash).build_transaction({
            "from": Web3.to_checksum_address(wallet),
            "nonce": w3.eth.get_transaction_count(Web3.to_checksum_address(wallet)),
            "gas": 200000,
            "gasPrice": w3.eth.gas_price
        })
        
        signed_tx = w3.eth.account.sign_transaction(tx, private_key)
        tx_hash = w3.eth.send_raw_transaction(signed_tx.raw_transaction)
        
        return {
            "success": True,
            "tx_hash": tx_hash.hex(),
            "mode": "live",
            "property_hash": property_hash
        }
        
    except Exception as e:
        return {
            "success": False,
            "tx_hash": None,
            "mode": "error",
            "message": str(e)
        }

def check_verification_on_chain(property_hash: str) -> dict:
    """
    Checks if a property hash is verified on-chain.
    """
    contract = _get_contract()
    if not contract:
        return {"verified": False, "mode": "offline"}
    
    try:
        is_verified = contract.functions.isVerified(property_hash).call()
        if is_verified:
            ph, verified_by, timestamp = contract.functions.getVerification(property_hash).call()
            return {
                "verified": True,
                "mode": "live",
                "verified_by": verified_by,
                "timestamp": timestamp,
                "property_hash": ph
            }
        return {"verified": False, "mode": "live"}
    except Exception as e:
        return {"verified": False, "mode": "error", "message": str(e)}
