# Global Constants

# Currency
DEFAULT_CURRENCY = "INR"

# Pagination
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

# Geo
DEFAULT_RADIUS_METERS = 5000
EARTH_RADIUS_KM = 6371

# Blockchain
POLYGON_AMOY_CHAIN_ID = 80002
POLYGON_MAINNET_CHAIN_ID = 137

# AI
PREDICTION_CONFIDENCE_THRESHOLD = 0.75
